### ISSUE TITLE
titleField vs fieldTitle

### ISSUE THREAD

**Issue by mewolari** [yogoo/sitemapFriend#1]
After installing sitemapFriend 3 errors occur on the sitemap-page

Notice: Undefined index: titleField in /mywebsite/core/components/sitemapfriend/model/sitemapfriend/sitemapfriend.class.php on line 67
/mywebsite/core/components/sitemapfriend/model/sitemapfriend/sitemapfriend.class.php on line 68
/mywebsite/core/components/sitemapfriend/model/sitemapfriend/sitemapfriend.class.php on line 69

In documentation http://rtfm.modx.com/display/ADDON/sitemapFriend Output Property fieldTitle is used. In sitemapfriend.class.php however titleField is used.

When I change [[!sitemapFriend? &type=`html`]] in [[!sitemapFriend? &type=`html` &titleField=`pagetitle`]] the problem is solved.

**Comment by yogoo** [comment]
Good catch, the doc is updated. Thanks for reporting the typo!

**Comment by mewolari** [comment]
Good morning, 

when I read your reaction it looks like only the doc is updated and not the software itself.

However, with using titleField on my site sitemapFriend gave the error as mentioned above. So I think there is also a small error in the software as well.

Joost

**Comment by yogoo** [comment]
Hi Joost,

You're right. I published a new version with a fix (v1.0.0-rc1).

You should be able to update sitemapFriend from the manager. If Modx fails to detect the new version, remove the existing one and redownload/reinstall.

Please let me know if this fixes your issue.

Jérôme

**Comment by mewolari** [comment]
Hi Jérôme,

problem solved!

Joost

Op 8 nov. 2012, om 22:58 heeft Jérôme Perrin notifications@github.com het volgende geschreven:
