### ISSUE TITLE
onlyTemplates does not work for children

### ISSUE THREAD

**Issue by gva230** [yogoo/sitemapFriend#10]
I use **onlyTemplates** option for child resources that have a parent with a no template... Well, it's easier to draw.
Site tree:
```
- someTemplate_id1
- parentNoTemplate
   - childTemplate_id3
   - childTemplate_id3
   - childTemplate_id3
- anotherTemplate_id2
```
sitemapFriend options:
```
[[!sitemapFriend?
    &onlyTemplates=`1,3`
    &type=`xml`
]]
```
In the output, I want to get all resources with a template called someTemplate and childTemplate. But I don't get resources with a template called childTemplate.

To work around this problem, you have to set the parent some template and specify the **skipResources** option for it. And everything would be fine, but I have a big multilingual site with a lot of contexts and only one sitemap.xml for all langs.

**Comment by yogoo** [comment]
Please note that this MODX Extra is not supported anymore. Feel free to fork it.
