### ISSUE TITLE
Property for exclusion of resources class modWebLink 

### ISSUE THREAD

**Issue by hansek** [yogoo/sitemapFriend#2]
Hi,
would be great if you implemented property to include resources with resource class modWebLink in rendered sitemap or not. 

Current automatic exclusion isn't good in some cases, for example I use webLinks to automatic redirect across MODX resources. Without PHP comment of line 98 in _sitemapfriend.class.php_ is this snippet unusable for me.

https://github.com/yogoo/sitemapFriend/blob/master/core/components/sitemapfriend/model/sitemapfriend/sitemapfriend.class.php#L98

```
$this->queryWhere = array(
    'modResource.class_key:!=' => 'modWebLink',
);
```

What do you think:question:

**Comment by yogoo** [comment]
Hi Jan, the extra is updated with a new property: includeWebLinks. Default is false for backward compatibility.

Thanks for the case example and code inclusion. That's awesome and made it easier/faster to implement.
