### ISSUE TITLE
Sitemap empty

### ISSUE THREAD

**Issue by iparr** [yogoo/sitemapFriend#3]
I've added this plugin to a standard MODx website, about 50 pages, all published. I'm calling the snippet thus; `[[!sitemapFriend? &type=`xml`]]`

The page returns the message "error on line 1 at column 1: Document is empty" and the file contains  `sitemapfriend.error.loadingclass`.

Any ideas why this is happening?

**Comment by yogoo** [comment]
The snippet can't load the class. There's not enough info in your message to make a full diagnosis so, I'd recommend you to remove the package completely and reinstall.

If you get the same error again, kindly provide me with more info about your configuration:
- server + version,
- php version (fpm?)
- apc,
- modx version
- sitemapFriend version

**Comment by iparr** [comment]
Hi @yogoo 

I guess remove and re-install is fundamental stuff! I did that and it works perfectly again, cheers.

What's odd is I usually don't need to do this. I moved servers (from my local dev to my remote production) and usually I don't have to do this with any plug-ins/snippets. I'm using the usual stuff (Wayfinder, getResources, etc.) and if I moved my site and database over using the recommended method ( http://rtfm.modx.com/display/revolution20/Moving+Your+Site+to+a+New+Server ). Do you have any idea why this is the case with sitemapFiend?

In case it helps anyone else, my details are as follows:
- Apache 2.2.18
- PHP 5.3.6 (although MODx reports as 5.3.10?)
- MySQL 5.1.62-cll
- No idea what APC is!
- MODx 2.2.6-pl (traditional)
- sitemapFriend 1.01

**Comment by yogoo** [comment]
It's hard to say without seeing your install and knowing its history. I remember having to remove/reinstall all plugins on certain server moves with pre 2.2.6 versions of Modx. My guess is that you updated from 2.2.5 or prior and that some namespaces path did not update properly.

APC is a [php accelerator](http://en.wikipedia.org/wiki/PHP_accelerator). I should have written php accelerator instead.
