### ISSUE TITLE
page do not validate as sitemap in google webmaster tools

### ISSUE THREAD

**Issue by AmaZili** [yogoo/sitemapFriend#4]
When using it in a revo page as xml page with empty template and content as : [[!sitemapFriend? &type=`xml`]]

upon google webmaster tools, I get the following : 

Avertissements

Balise XML incorrecte

Cette balise n'a pas été reconnue. Corrigez le problème et réessayez.

98

Balise parent : url
Tag : title

9

2 avr. 2013

and it seems there is no way to change the xml template for the xml item.

**Comment by yogoo** [comment]
Thanks for providing the error. However I'll need more info to figure out what's happening. Can you post the url to your sitemap and/or its full xml code.

**Comment by iparr** [comment]
This was highlighted to me by Google Webmaster tools as well.

After attempting to validate it, using this tool ( http://www.validome.org/xml/validate/ ), it seems that the default sitemap_xml_outer.chunk.tpl is producing invalid XML.

This is because sitemapFriend is starting the xml document with a break. This is invalid.

I've removed this manually, but it's still not invalid XML due to:

```
Can not find declaration of element 'urlset'.
    Error Position: 
xmlns:dc="http://purl.org/dc/elements/1.1/">
```

I have no idea about this one! If it helps, my problematic sitemap is here: http://tedxsheffield.com/sitemap.xml

**Comment by yogoo** [comment]
@iparr, I as said before, kindly post the url to the sitemap or its full code. I can't investigate the issue without it.

**Comment by iparr** [comment]
@yogoo , the sitemap is message posted previously: http://tedxsheffield.com/sitemap.xml The call is exactly the same as @ArtImpulsion s and is using all the default tpls, etc. Can I help you with any further details?

**Comment by yogoo** [comment]
Whoops, missed the url... Thanks for re-posting it.

Here's what I found so far:
- the tool you use marks the [example sitemap provided by Google](http://support.google.com/webmasters/bin/answer.py?hl=en&answer=183668) as invalid. However both Google example and sitemapFriend's sitemaps validate under W3C's validator.
- there's no new line character at the beginning of the output. The one you see is most likely added when copying the content of the page. See the page source or the response from the server.
- can you post the exact error returned by Google Webmaster tools?

@ArtImpulsion : you're right, the xml output is not configurable.

**Comment by AmaZili** [comment]
Hi,

on my side google webmaster tools refused to validate the xml sitemap generated due to the presence of the dublin core stuff.
I managed to change direclty in the core directory (core / components / sitemapfriend / elements / chunks / sitemap_xml_item.chunk.tpl & sitemap_xml_outer.chunk.tpl) the xml templates (ooooh ! bad boy) and remove DC references from there, and it validates fine. 

Next release could have the xml templates as parameters to avoid any troubles.

Thanks anyway....

**Comment by iparr** [comment]
> there's no new line character at the beginning of the output. The one you see is most likely added when copying the content of the page. See the page source or the response from the server.

Yup. doh.

> can you post the exact error returned by Google Webmaster tools?

Under 'Error details' in 'Sitemaps':
Invalid XML tag - This tag was not recognized. Please fix it and resubmit.

Sorry, not very good details but that's the best I can do. Thank you for editing the default tpl.

**Comment by yogoo** [comment]
@iparr: v1.0.2 should fix your issue.

**Comment by AmaZili** [comment]
Merci Jérome.
