### ISSUE TITLE
Unable to install sitemapfriend

### ISSUE THREAD

**Issue by mewolari** [yogoo/sitemapFriend#6]
Both on a localhost as on modxcloud unable to install sitemapfriend.

Error reported on modxcloud:

Console running...
Attempting to install package with signature: sitemapfriend-1.0.2-pl1
Package found...now preparing to install.
Could not find package manifest at /paas/c0302/www/core/packages/sitemapfriend-1.0.2-pl1/manifest.php
Could not unpack package /paas/c0302/www/core/packages/sitemapfriend-1.0.2-pl1.transport.zip to /paas/c0302/www/core/packages/. SIG: sitemapfriend-1.0.2-pl1
Could not install package with signature: sitemapfriend-1.0.2-pl1

**Comment by iparr** [comment]
Are you able to install any similar packages via the package manager?

**Comment by mewolari** [comment]
Looks like it was a temporary problem.

I was not able to install the package from both localhost and modxcloud.

Afterwards installing was not any problem anymore.

Other packages were not giving problems.

Op 12 feb. 2014, om 18:00 heeft Ian notifications@github.com het volgende geschreven:
