### ISSUE TITLE
Displays only top level documents, unless specified in includeResources

### ISSUE THREAD

**Issue by tourshi** [yogoo/sitemapFriend#7]
using modx 2.2.9
on windows enviornment,
apache mysql php5

**Comment by yogoo** [comment]
I could **not** reproduce your issue on modx 2.2.12-pl (traditional) where sitemapFriend works well.

**Comment by sonicpunk** [comment]
I am also having an issue with my modx install 2.2.13.  The XML output is not reflecting the structure of the website.  It is ignoring the parent child relationship and not showing the parent in the link.  It also does not show all of the pages.  I had the same issue with googleSitemap and tried this add-on to see if it would make a difference, but it does not.  

My content type is set to XML in the resource settings.  Strangely enough if I change the resource content type setting to HTML, the snippet does show the correct sitemap - including folders.

My snippet call is this:
[[!sitemapFriend? &startId=`0` &type=`xml` &showHidden=`true` &onlySearchable=`false` &urlScheme=`full` &maxDepth=`0`]]

**Comment by osabate** [comment]
I'm having the same issue with ModX 2.2.15
It doesn't when setting the type to HTML either.

This is a sample call:

[[sitemapFriend? 
&type=`xml` 
&maxDepth=`0` 
&onlySearchable=`true` 
&showHidden=`true` 
&showUpublished=`false`
&showDeleted=`false`
&sortBy=`menuindex` 
&sortDir=`ASC` 
&skipTemplates=`10,11,13` 
&includeWebLinks=`false` ]]

**Comment by yogoo** [comment]
I won't be able to look into it any time soon. Can you submit a pull request?
