### ISSUE TITLE
li style

### ISSUE THREAD

**Issue by hcanning2014** [yogoo/sitemapFriend#8]
Thought this should work `[[sitemapFriend? &type=`html` &tplOuter=`sitemap` &tplItem=`sitemap-li`]]`

with sitemap-li chunk =

```
<li class="list-group">
    <a href="[[+url]]">[[+title]]</a>
    [[+items]]
</li>
```

...but doesnt render with class="list-group on frontend

`tplOuter=`sitemap` works fine`

**Comment by yogoo** [comment]
Can you post the output of the relevant code?
