### ISSUE TITLE
Exclude error pages in contexts

### ISSUE THREAD

**Issue by gva230** [yogoo/sitemapFriend#9]
I have a multilingual site, where each language is in its own context. Each context has its own error pages. System settings for error page numbers are not used. However sitemapFriend excludes those error pages that are specified in the system settings, but does not excludes those specified in the context settings.

The problem is that if you do not specify any unnecessary IDs (for example, real error pages) in the system settings, then you can get the result without a resource with ID 1 or another ID that is specified there. Аnd you will catch this bug for a very long time. If you notice it, of course.

**Comment by yogoo** [comment]
Please note that this MODX Extra is not supported anymore. Feel free to fork it.
